name: SSA
services:
  php:
    container_name: php
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ../
        target: /ssapp
      - type: bind
        source: ./php/default.conf
        target: /etc/apache2/sites-enabled/000-default.conf
      - type: volume
        source: ssapp-vendor
        target: /ssapp/app/vendor
      - type: volume
        source: node_modules
        target: /ssapp/app/node_modules
      - type: volume
        source: codex-data
        target: /root/.codex
    ports:
      - "80:80"
      - "5173:5173"
    tty: true
    # environment:
      # - XDEBUG_MODE=debug
    depends_on:
      - mysql
    networks:
      - ssapp-network
  
  mysql:
    container_name: mysql
    build:
      context: ./mysql
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: employee_search
      MYSQL_USER: mysql
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - type: volume
        source: mysql-data
        target: /var/lib/mysql
      - type: bind
        source: ./mysql/init.sql
        target: /docker-entrypoint-initdb.d/init.sql
    networks:
      - ssapp-network

volumes:
  node_modules:
  mysql-data:
  ssapp-vendor:
  codex-data:

networks:
  ssapp-network: